name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_IMAGE_NAME: ${{secrets.DOCKER_IMAGE_NAME}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v6.0.2
      with:
        major_pattern: "major:"
        minor_pattern: "/feat(\\(.+\\))?:/"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    - name: Docker login
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker build -t $DOCKER_IMAGE_NAME:$NEW_VERSION .
        docker build -t $DOCKER_IMAGE_NAME:latest .
      
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker push $DOCKER_IMAGE_NAME:$NEW_VERSION
        docker push $DOCKER_IMAGE_NAME:latest
